
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rainier
 */
public class InsertBillFrame extends javax.swing.JFrame {

    /**
     * Creates new form InsertBillFrame
     */
    public InsertBillFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bill_number_textfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bill_name_textarea = new javax.swing.JTextArea();
        senate_radio = new javax.swing.JRadioButton();
        house_radio = new javax.swing.JRadioButton();
        first_radio = new javax.swing.JRadioButton();
        second_radio = new javax.swing.JRadioButton();
        filed_by_textfield = new javax.swing.JTextField();
        filed_at_senate = new javax.swing.JRadioButton();
        filed_at_house = new javax.swing.JRadioButton();
        month_select = new javax.swing.JComboBox<>();
        day_select = new javax.swing.JComboBox<>();
        year_select = new javax.swing.JComboBox<>();
        insert_button = new javax.swing.JButton();
        close_button = new javax.swing.JButton();
        third_radio = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        approved_radio = new javax.swing.JRadioButton();
        pending_radio = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bill Number: ");

        jLabel2.setText("Bill Name: ");

        jLabel3.setText("Approved in:");

        jLabel4.setText("Hearing number:");

        jLabel5.setText("Filed by:");

        jLabel6.setText("Filed at:");

        jLabel7.setText("Date filed:");

        bill_name_textarea.setColumns(20);
        bill_name_textarea.setLineWrap(true);
        bill_name_textarea.setRows(5);
        jScrollPane1.setViewportView(bill_name_textarea);

        buttonGroup2.add(senate_radio);
        senate_radio.setSelected(true);
        senate_radio.setText("Senate");
        senate_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senate_radioActionPerformed(evt);
            }
        });

        buttonGroup2.add(house_radio);
        house_radio.setText("House of Representatives");
        house_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                house_radioActionPerformed(evt);
            }
        });

        buttonGroup1.add(first_radio);
        first_radio.setSelected(true);
        first_radio.setText("First");
        first_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_radioActionPerformed(evt);
            }
        });

        buttonGroup1.add(second_radio);
        second_radio.setText("Second");
        second_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                second_radioActionPerformed(evt);
            }
        });

        buttonGroup3.add(filed_at_senate);
        filed_at_senate.setSelected(true);
        filed_at_senate.setText("Senate");
        filed_at_senate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filed_at_senateActionPerformed(evt);
            }
        });

        buttonGroup3.add(filed_at_house);
        filed_at_house.setText("House of Representatives");
        filed_at_house.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filed_at_houseActionPerformed(evt);
            }
        });

        month_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        month_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month_selectActionPerformed(evt);
            }
        });

        day_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day_select.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        year_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));
        year_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_selectActionPerformed(evt);
            }
        });

        insert_button.setText("Insert");
        insert_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_buttonActionPerformed(evt);
            }
        });

        close_button.setText("Cancel");
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(third_radio);
        third_radio.setText("Third");

        jLabel8.setText("Status:");

        buttonGroup4.add(approved_radio);
        approved_radio.setSelected(true);
        approved_radio.setText("Approved");

        buttonGroup4.add(pending_radio);
        pending_radio.setText("Pending");

        buttonGroup4.add(jRadioButton1);
        jRadioButton1.setText("Rejected");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(insert_button, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close_button, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(filed_at_senate)
                            .addGap(30, 30, 30)
                            .addComponent(filed_at_house))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(first_radio)
                                .addGap(18, 18, 18)
                                .addComponent(second_radio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(third_radio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(senate_radio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(house_radio))
                            .addComponent(bill_number_textfield)
                            .addComponent(jScrollPane1)
                            .addComponent(filed_by_textfield)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(month_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(approved_radio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pending_radio)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(day_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(year_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bill_number_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senate_radio)
                    .addComponent(jLabel3)
                    .addComponent(house_radio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(first_radio)
                        .addComponent(second_radio)
                        .addComponent(third_radio))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(filed_by_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(filed_at_house)
                    .addComponent(filed_at_senate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(month_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(day_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(year_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(approved_radio)
                        .addComponent(pending_radio)
                        .addComponent(jRadioButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert_button)
                    .addComponent(close_button))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senate_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senate_radioActionPerformed

    }//GEN-LAST:event_senate_radioActionPerformed

    private void house_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_house_radioActionPerformed

    }//GEN-LAST:event_house_radioActionPerformed

    private void second_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_second_radioActionPerformed
      
    }//GEN-LAST:event_second_radioActionPerformed

    private void first_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_radioActionPerformed

    }//GEN-LAST:event_first_radioActionPerformed

    private void filed_at_senateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filed_at_senateActionPerformed

    }//GEN-LAST:event_filed_at_senateActionPerformed

    private void filed_at_houseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filed_at_houseActionPerformed

    }//GEN-LAST:event_filed_at_houseActionPerformed

    private void month_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month_selectActionPerformed

    }//GEN-LAST:event_month_selectActionPerformed

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
       this.dispose();
    }//GEN-LAST:event_close_buttonActionPerformed

    private void year_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_selectActionPerformed

    }//GEN-LAST:event_year_selectActionPerformed

    private void insert_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_buttonActionPerformed
        String temp = filed_by_textfield.getText();
        boolean found = false;
        try {   
            String url = "jdbc:mysql://localhost:3306/bill_info_system?zeroDateTimeBehavior=convertToNull";
            java.sql.Connection conn = DriverManager.getConnection(url,"root","admin");
            java.sql.Statement stmt = conn.createStatement();
            ResultSet rs;
 
            rs = stmt.executeQuery("SELECT * FROM senator where name='"+temp+"';");
            while ( rs.next() ) {
                String senator_id = rs.getString("senator_id");
                String name = rs.getString("name");
                String position = rs.getString("position_in_senate");
                found = true;
            }
            conn.close();
        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
        try {   
            String url = "jdbc:mysql://localhost:3306/bill_info_system?zeroDateTimeBehavior=convertToNull";
            java.sql.Connection conn = DriverManager.getConnection(url,"root","admin");
            java.sql.Statement stmt = conn.createStatement();
            ResultSet rs;
 
            rs = stmt.executeQuery("SELECT * FROM congressman where name='"+temp+"';");
            while ( rs.next() ) {
                String senator_id = rs.getString("congressman_id");
                String name = rs.getString("name");
                String position = rs.getString("position_in_congress");
                found = true;
            }
            conn.close();
        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
        if(!found){
            new NotInDB().setVisible(true);
        }else if(bill_number_textfield.getText().toString().equals("") || bill_name_textarea.getText().toString().equals("")||filed_by_textfield.getText().toString().equals("")){
            new InputNull().setVisible(true);
        }else if(bill_number_textfield.getText().toString().matches("^[0-9]+$") && filed_by_textfield.getText().matches("^[a-zA-Z0-9_?,\"'. ]*$")){
            String bill_no_str=bill_number_textfield.getText();
            String bill_name_str=bill_name_textarea.getText();
            String approved_in_str;
            String hearing_no;
            String filed_by_str=filed_by_textfield.getText();
            String filed_at_str;
            String date_filed_str = month_select.getSelectedItem().toString()+" "+day_select.getSelectedItem().toString()+" "+year_select.getSelectedItem().toString();
            System.out.println(date_filed_str);
            String bill_status_str;
            
            if(first_radio.isSelected()){
                hearing_no = "First";
            }else if(second_radio.isSelected()){
                hearing_no = "Second";
            }else{
                hearing_no = "Third";
            }
            
            if(senate_radio.isSelected()){
                approved_in_str = "Senate";
            }else{
                approved_in_str = "House of Representatives";
            }
            if(filed_at_senate.isSelected()){
                filed_at_str = "Senate";
            }else{
                filed_at_str = "House of Representatives";
            }
            if(approved_radio.isSelected()){
                bill_status_str = "Approved";
            }else if(pending_radio.isSelected()){
                bill_status_str = "Pending";
            }else{
                bill_status_str= "Rejected";
            }
            try {
            String url = "jdbc:mysql://localhost:3306/bill_info_system?zeroDateTimeBehavior=convertToNull";
            try (Connection conn = (Connection) DriverManager.getConnection(url,"root","admin")) {
                Statement stmt = (Statement) conn.createStatement();
                int rows;
                                                                                                                                                        //bill_no str,bill_name_str,approved_in_str,hearing_no,filed_by_str,filed_at_str,date_filed_str
                String insert = "insert into bill(bill_no, bill_name, hearing_number, filed_by, filed_at, date_filed, bill_status, approved_in) values ('"+bill_no_str+"', '"+bill_name_str+"', '"+hearing_no+"', '"+filed_by_str+"', '"+filed_at_str+"', str_to_date('"+date_filed_str+"','%M %d %Y'), '"+bill_status_str+"','"+approved_in_str+"');";
                rows = stmt.executeUpdate(insert);
            }
            this.dispose();
        } catch (SQLException e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
        }else{
            new NameInputError().setVisible(true);
        }
    }//GEN-LAST:event_insert_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertBillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertBillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertBillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertBillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertBillFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton approved_radio;
    private javax.swing.JTextArea bill_name_textarea;
    private javax.swing.JTextField bill_number_textfield;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton close_button;
    private javax.swing.JComboBox<String> day_select;
    private javax.swing.JRadioButton filed_at_house;
    private javax.swing.JRadioButton filed_at_senate;
    private javax.swing.JTextField filed_by_textfield;
    private javax.swing.JRadioButton first_radio;
    private javax.swing.JRadioButton house_radio;
    private javax.swing.JButton insert_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> month_select;
    private javax.swing.JRadioButton pending_radio;
    private javax.swing.JRadioButton second_radio;
    private javax.swing.JRadioButton senate_radio;
    private javax.swing.JRadioButton third_radio;
    private javax.swing.JComboBox<String> year_select;
    // End of variables declaration//GEN-END:variables
}
