
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rainier
 */
public class UpdateBill extends javax.swing.JFrame {

    /**
     * Creates new form UpdateBill
     */
    public UpdateBill() {
        initComponents();
        addToDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        id_textfield = new javax.swing.JTextField();
        enter_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bill_num_textfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bill_name_textarea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ai_senate = new javax.swing.JRadioButton();
        ai_congress = new javax.swing.JRadioButton();
        first_radio = new javax.swing.JRadioButton();
        second_radio = new javax.swing.JRadioButton();
        third_radio = new javax.swing.JRadioButton();
        filed_by_textfield = new javax.swing.JTextField();
        fa_senate = new javax.swing.JRadioButton();
        fa_congress = new javax.swing.JRadioButton();
        month = new javax.swing.JComboBox<>();
        day = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        approved_radio = new javax.swing.JRadioButton();
        pending_radio = new javax.swing.JRadioButton();
        rejected_radio = new javax.swing.JRadioButton();
        update_button = new javax.swing.JButton();
        close_button = new javax.swing.JButton();
        scrollpane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter ID:");

        enter_button.setText("Enter");
        enter_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_buttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Billl Number:");

        jLabel3.setText("Bill Name:");

        bill_name_textarea.setColumns(20);
        bill_name_textarea.setLineWrap(true);
        bill_name_textarea.setRows(5);
        jScrollPane2.setViewportView(bill_name_textarea);

        jLabel4.setText("Approved in:");

        jLabel5.setText("Hearing number:");

        jLabel6.setText("Filed by:");

        jLabel7.setText("Filed at:");

        jLabel8.setText("Date filed:");

        jLabel9.setText("Status:");

        buttonGroup1.add(ai_senate);
        ai_senate.setText("Senate");

        buttonGroup1.add(ai_congress);
        ai_congress.setText("House of Representatives");

        buttonGroup2.add(first_radio);
        first_radio.setText("First");

        buttonGroup2.add(second_radio);
        second_radio.setText("Second");

        buttonGroup2.add(third_radio);
        third_radio.setText("Third");

        buttonGroup3.add(fa_senate);
        fa_senate.setText("Senate");

        buttonGroup3.add(fa_congress);
        fa_congress.setText("House of Representatives");

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));

        buttonGroup4.add(approved_radio);
        approved_radio.setText("Approved");

        buttonGroup4.add(pending_radio);
        pending_radio.setText("Pending");

        buttonGroup4.add(rejected_radio);
        rejected_radio.setText("Rejected");

        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        close_button.setText("Close");
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill #", "Bill name", "Hearing #", "Approved in", "Filed by", "Filed at", "Date filed", "Bill status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpane.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(1).setPreferredWidth(200);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(2).setPreferredWidth(50);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(4).setPreferredWidth(200);
            table.getColumnModel().getColumn(5).setResizable(false);
            table.getColumnModel().getColumn(6).setResizable(false);
            table.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(bill_num_textfield))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enter_button))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(ai_senate)
                                .addGap(18, 18, 18)
                                .addComponent(ai_congress))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(first_radio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(second_radio)
                                .addGap(18, 18, 18)
                                .addComponent(third_radio))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(fa_senate)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(fa_congress))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(approved_radio)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(pending_radio)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(rejected_radio))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(filed_by_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(221, 221, 221))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(update_button)
                                        .addGap(121, 121, 121)
                                        .addComponent(close_button)
                                        .addGap(364, 364, 364))))))
                    .addComponent(scrollpane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bill_num_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ai_senate)
                    .addComponent(ai_congress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(first_radio)
                        .addComponent(second_radio)
                        .addComponent(third_radio)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(filed_by_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fa_senate)
                            .addComponent(fa_congress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(approved_radio)
                            .addComponent(pending_radio)
                            .addComponent(rejected_radio))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_button)
                    .addComponent(close_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_close_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        String temp = filed_by_textfield.getText();
        boolean found = false;
        //finds the filed_by variable in the list of senators and house reps
        try {   
            String url = "jdbc:mysql://localhost:3306/bill_info_system?zeroDateTimeBehavior=convertToNull";
            java.sql.Connection conn = DriverManager.getConnection(url,"root","admin");
            java.sql.Statement stmt = conn.createStatement();
            ResultSet rs;
 
            rs = stmt.executeQuery("SELECT * FROM senator where name='"+temp+"';");
            while ( rs.next() ) {
                String senator_id = rs.getString("senator_id");
                String name = rs.getString("name");
                String position = rs.getString("position_in_senate");
                found = true;
            }
            conn.close();
        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
        try {   
            String url = "jdbc:mysql://localhost:3306/bill_info_system?zeroDateTimeBehavior=convertToNull";
            java.sql.Connection conn = DriverManager.getConnection(url,"root","admin");
            java.sql.Statement stmt = conn.createStatement();
            ResultSet rs;
 
            rs = stmt.executeQuery("SELECT * FROM congressman where name='"+temp+"';");
            while ( rs.next() ) {
                String senator_id = rs.getString("congressman_id");
                String name = rs.getString("name");
                String position = rs.getString("position_in_congress");
                found = true;
            }
            conn.close();
        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
        //if not author not in database
        if(!found){
            new NotInDB().setVisible(true);
        }else if(bill_num_textfield.getText().toString().equals("") || bill_name_textarea.getText().toString().equals("")||filed_by_textfield.getText().toString().equals("")){
            new InputNull().setVisible(true); //if one of textfields are empty
        }else if(bill_num_textfield.getText().toString().matches("^[0-9]+$") && filed_by_textfield.getText().matches("^[a-zA-Z0-9_?,\"'. ]*$")){
            String bill_no_str=bill_num_textfield.getText();
            String bill_name_str=bill_name_textarea.getText();
            String approved_in_str;
            String hearing_no;
            String filed_by_str=filed_by_textfield.getText();
            String filed_at_str;
            String date_filed_str = month.getSelectedItem().toString()+" "+day.getSelectedItem().toString()+" "+year.getSelectedItem().toString();
            System.out.println(date_filed_str);
            String bill_status_str;
            
            if(first_radio.isSelected()){
                hearing_no = "First";
            }else if(second_radio.isSelected()){
                hearing_no = "Second";
            }else{
                hearing_no = "Third";
            }
            
            if(ai_senate.isSelected()){
                approved_in_str = "Senate";
            }else{
                approved_in_str = "House of Representatives";
            }
            if(fa_senate.isSelected()){
                filed_at_str = "Senate";
            }else{
                filed_at_str = "House of Representatives";
            }
            if(approved_radio.isSelected()){
                bill_status_str = "Approved";
            }else if(pending_radio.isSelected()){
                bill_status_str = "Pending";
            }else{
                bill_status_str= "Rejected";
            }
            try {
            String url = "jdbc:mysql://localhost:3306/bill_info_system?zeroDateTimeBehavior=convertToNull";
            try (com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(url,"root","admin")) {
                com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) conn.createStatement();
                ResultSet rs;
                int rows;
                                                                                                                                                        //bill_no str,bill_name_str,approved_in_str,hearing_no,filed_by_str,filed_at_str,date_filed_str
                String update = "update bill set bill_no='"+bill_no_str+"',bill_name='"+bill_name_str+"',approved_in='"+approved_in_str+"',hearing_number='"+hearing_no+"',filed_by='"+filed_by_str+"',date_filed=str_to_date('"+date_filed_str+"','%M %d %Y'),bill_status='"+bill_status_str+"' where bill_no ='"+bill_no_str+"';";
                rows = stmt.executeUpdate(update);
                addToDisplay();
            }
            this.dispose();
        } catch (SQLException e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
        }else{
            new NameInputError().setVisible(true);
        }
    }//GEN-LAST:event_update_buttonActionPerformed

    private void enter_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_buttonActionPerformed
        String id = id_textfield.getText().toString();
        boolean notFound = true;
        try {   
            String url = "jdbc:mysql://localhost:3306/bill_info_system?zeroDateTimeBehavior=convertToNull";
            Connection conn = DriverManager.getConnection(url,"root","admin");
            Statement stmt = conn.createStatement();
            ResultSet rs;
 
            rs = stmt.executeQuery("SELECT * FROM bill;");
            while ( rs.next() ) {
                String bill_no = rs.getString("bill_no");
                String bill_name = rs.getString("bill_name");
                String hearing_number = rs.getString("hearing_number");
                String approved_in = rs.getString("approved_in");
                String filed_by = rs.getString("filed_by");
                String filed_at = rs.getString("filed_at");
                String date_filed = rs.getString("date_filed");
                String bill_status = rs.getString("bill_status");
                String date[] = date_filed.split("-");//splits date
                //assigns vars according to radio buttons;
                if(bill_no.equals(id)){
                    bill_name_textarea.setText(bill_name);
                    filed_by_textfield.setText(filed_by);
                    bill_num_textfield.setText(bill_no);
                    if(hearing_number.equals("First")){
                        first_radio.setSelected(true);
                    }else if(hearing_number.equals("Second")){
                        second_radio.setSelected(true);
                    }else{
                        third_radio.setSelected(true);
                    }
                    if(approved_in.equals("House of Representatives")){
                        ai_congress.setSelected(true);
                    }else{
                        ai_senate.setSelected(true);
                    }
                    if(filed_at.equals("House of Representatives")){
                        fa_congress.setSelected(true);
                    }else{
                        fa_senate.setSelected(true);
                    }
                    if(bill_status.equals("Approved")){
                        approved_radio.setSelected(true);
                    }else if(bill_status.equals("Pending")){
                        pending_radio.setSelected(true);
                    }else{
                        rejected_radio.setSelected(true);
                    }
                    //converts combobox to date
                    switch(date[1]){
                        case "01": month.setSelectedIndex(0); break;
                        case "02": month.setSelectedIndex(1); break;
                        case "03": month.setSelectedIndex(2); break;
                        case "04": month.setSelectedIndex(3); break;
                        case "05": month.setSelectedIndex(4); break;
                        case "06": month.setSelectedIndex(5); break;
                        case "07": month.setSelectedIndex(6); break;
                        case "08": month.setSelectedIndex(7); break;
                        case "09": month.setSelectedIndex(8); break;
                        case "10": month.setSelectedIndex(9); break;
                        case "11": month.setSelectedIndex(10); break;
                        case "12": month.setSelectedIndex(11);break;
                    }
                    switch(date[2]){
                        case "01": day.setSelectedIndex(0); break;
                        case "02": day.setSelectedIndex(1); break;
                        case "03": day.setSelectedIndex(2); break;
                        case "04": day.setSelectedIndex(3); break;
                        case "05": day.setSelectedIndex(4); break;
                        case "06": day.setSelectedIndex(5); break;
                        case "07": day.setSelectedIndex(6); break;
                        case "08": day.setSelectedIndex(7); break;
                        case "09": day.setSelectedIndex(8); break;
                        case "10": day.setSelectedIndex(9); break;
                        case "11": day.setSelectedIndex(10);break;
                        case "12": day.setSelectedIndex(11);break;
                        case "13": day.setSelectedIndex(12);break;
                        case "14": day.setSelectedIndex(13);break;
                        case "15": day.setSelectedIndex(14);break;
                        case "16": day.setSelectedIndex(15);break;
                        case "17": day.setSelectedIndex(16);break;
                        case "18": day.setSelectedIndex(17);break;
                        case "19": day.setSelectedIndex(18);break;
                        case "20": day.setSelectedIndex(19);break;
                        case "21": day.setSelectedIndex(20);break;
                        case "22": day.setSelectedIndex(21);break;
                        case "23": day.setSelectedIndex(22);break;
                        case "24": day.setSelectedIndex(23);break;
                        case "25": day.setSelectedIndex(24);break;
                        case "26": day.setSelectedIndex(25);break;
                        case "27": day.setSelectedIndex(26);break;
                        case "28": day.setSelectedIndex(27);break;
                        case "29": day.setSelectedIndex(28);break;
                        case "30": day.setSelectedIndex(29);break;
                        case "31": day.setSelectedIndex(30);break;
                    }
                    switch(date[0]){
                        case "1980": year.setSelectedIndex(0);break;
                        case "1981": year.setSelectedIndex(1);break;
                        case "1982": year.setSelectedIndex(2);break;
                        case "1983": year.setSelectedIndex(3);break;
                        case "1984": year.setSelectedIndex(4);break;
                        case "1985": year.setSelectedIndex(5);break;
                        case "1986": year.setSelectedIndex(6);break;
                        case "1987": year.setSelectedIndex(7);break;
                        case "1988": year.setSelectedIndex(8);break;
                        case "1989": year.setSelectedIndex(9);break;
                        case "1990": year.setSelectedIndex(10);break;
                        case "1991": year.setSelectedIndex(11);break;
                        case "1992": year.setSelectedIndex(12);break;
                        case "1993": year.setSelectedIndex(13);break;
                        case "1994": year.setSelectedIndex(14);break;
                        case "1995": year.setSelectedIndex(15);break;
                        case "1996": year.setSelectedIndex(16);break;
                        case "1997": year.setSelectedIndex(17);break;
                        case "1998": year.setSelectedIndex(18);break;
                        case "1999": year.setSelectedIndex(19);break;
                        case "2000": year.setSelectedIndex(20);break;
                        case "2001": year.setSelectedIndex(21);break;
                        case "2002": year.setSelectedIndex(22);break;
                        case "2003": year.setSelectedIndex(23);break;
                        case "2004": year.setSelectedIndex(24);break;
                        case "2005": year.setSelectedIndex(25);break;
                        case "2006": year.setSelectedIndex(26);break;
                        case "2007": year.setSelectedIndex(27);break;
                        case "2008": year.setSelectedIndex(28);break;
                        case "2009": year.setSelectedIndex(29);break;
                        case "2010": year.setSelectedIndex(30);break;
                        case "2011": year.setSelectedIndex(31);break;
                        case "2012": year.setSelectedIndex(32);break;
                        case "2013": year.setSelectedIndex(33);break;
                        case "2014": year.setSelectedIndex(34);break;
                        case "2015": year.setSelectedIndex(35);break;
                        case "2016": year.setSelectedIndex(36);break;
                        case "2017": year.setSelectedIndex(37);break;
                    }
                    notFound=false;
                }
            }
            conn.close();
        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
        if(notFound==true){
            new IDnotfound().setVisible(true);
            bill_name_textarea.setText("");
            filed_by_textfield.setText("");
            bill_num_textfield.setText("");
            first_radio.setSelected(false);
            second_radio.setSelected(false);
            third_radio.setSelected(false);
            ai_congress.setSelected(false);
            ai_senate.setSelected(false);
            fa_congress.setSelected(false);
            fa_senate.setSelected(false);
            approved_radio.setSelected(false);
            pending_radio.setSelected(false);
            rejected_radio.setSelected(false);
                    
        }
    }//GEN-LAST:event_enter_buttonActionPerformed
    private void addToDisplay(){
         try {   
            String url = "jdbc:mysql://localhost:3306/bill_info_system?zeroDateTimeBehavior=convertToNull";
             Connection conn = DriverManager.getConnection(url,"root","admin");
            Statement stmt = conn.createStatement();
            ResultSet rs;
 
            rs = stmt.executeQuery("SELECT * FROM bill;");
            while ( rs.next() ) {
                String bill_no = rs.getString("bill_no");
                String bill_name = rs.getString("bill_name");
                String hearing_number = rs.getString("hearing_number");
                String approved_in = rs.getString("approved_in");
                String filed_by = rs.getString("filed_by");
                String filed_at = rs.getString("filed_at");
                String date_filed = rs.getString("date_filed");
                String bill_status = rs.getString("bill_status");
                Object row[]={bill_no,bill_name,hearing_number,approved_in,filed_by,filed_at,date_filed,bill_status};
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                model.addRow(row);
       }
            conn.close();
        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ai_congress;
    private javax.swing.JRadioButton ai_senate;
    private javax.swing.JRadioButton approved_radio;
    private javax.swing.JTextArea bill_name_textarea;
    private javax.swing.JTextField bill_num_textfield;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton close_button;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JButton enter_button;
    private javax.swing.JRadioButton fa_congress;
    private javax.swing.JRadioButton fa_senate;
    private javax.swing.JTextField filed_by_textfield;
    private javax.swing.JRadioButton first_radio;
    private javax.swing.JTextField id_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JRadioButton pending_radio;
    private javax.swing.JRadioButton rejected_radio;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JRadioButton second_radio;
    private javax.swing.JTable table;
    private javax.swing.JRadioButton third_radio;
    private javax.swing.JButton update_button;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
